TheBlog/TheBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('posts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

TheBlog/posts/urls.py
from django.urls import path 
from posts.views import BlogHome, BlogPostCreate, BlogPostUpdate,BlogPostDetail,BlogPostDelete
from django.contrib.auth.decorators import login_required
from TheBlog import settings
from django.conf.urls.static import static
 

app_name = "posts"

urlpatterns = [
    path('',BlogHome.as_view(),name = 'home'),
    path('create/',BlogPostCreate.as_view(),name='create'),
    path('<str:slug>',BlogPostDetail.as_view(), name = "detail"),    
    path('edit/<str:slug>',BlogPostUpdate.as_view(),name = 'edit'),
    path('delete/<str:slug>/',BlogPostDelete.as_view(),name = 'delete'),
]

TheBlog/main/models.py
from django.db import models

# Create your models here.

TheBlog/posts/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.

User = get_user_model()

class BlogPost(models.Model):
    title = models.CharField(max_length = 255, unique = True, verbose_name = 'Titre')
    slug = models.SlugField(max_length = 255, unique = True, blank =True)
    author = models.ForeignKey(User,on_delete = models.SET_NULL, null = True, blank = True)
    last_updated = models.DateTimeField(auto_now = True)
    created_on = models.DateField(blank = True, null = True)
    published = models.BooleanField(default = False, verbose_name = 'Publier')
    content = models.TextField(blank = True, verbose_name = 'Contenu')
    thumbnail = models.ImageField(blank = True, upload_to = 'blog')

    class Meta:
        ordering = ['-created_on']
        verbose_name = 'Article'

    def __str__(self):
        return self.title

    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    @property
    def author_or_unnone(self):
        return self.author.username if self.author else " l'auteur inconnu "

    def get_absolute_url(self):
        return reverse('posts:home')

TheBlog/main/views.py
from django.shortcuts import render

# Create your views here.

TheBlog/posts/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView,UpdateView,DetailView,DeleteView
from posts.models import BlogPost
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class BlogHome(ListView):
    model = BlogPost
    context_object_name = 'posts'
    #filtre sur le query set ....
    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published = True)

@method_decorator(login_required, name ='dispatch')
class BlogPostCreate(CreateView):

    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ['title','content']

class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = "posts/blogpost_update.html"
    fields = ['title','content','published']

class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = "posts/blogpost_detail.html"
    context_object_name = 'post'
# Create your views here.


class BlogPostDelete(DeleteView):
    model = BlogPost
    
    success_url = reverse_lazy('posts:home')

TheBlog/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Supprimer un article 
{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p> Etes-vous sur de vouloir supprimer cette article ?</p>
        <input type="submit" value="oui, supprimer " class='btn btn-delete'>
    </form>
{% endblock %}

TheBlog/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title%}Ajouter un article{% endblock %}


{% block content%}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value = 'Creer' class='btn btn-submit'>
</form>
{% endblock %}

TheBlog/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}

    <article class = 'post-detail'>
        <h1>{{post.title}}</h1>
        <img src="{{post.thumbnail.url}}" alt="une image ">
        <div>{{post.content|linebreaks|safe}}</div>
    </article>

{% endblock %}

TheBlog/posts/templates/posts/blogpost_list.html
{% extends 'base.html'%}

{% block title%}
    Accueil du blog 
{% endblock %}

{% block content %}
    <h1>Le blog de KenStasera </h1>
    {% for post in posts %}
        <article>
            <div class = 'post-title'>
                <h2>{{post.title}}</h2>
                {% if request.user.is_authenticated %}
                <div>
                    <a href="{% url 'posts:edit' slug=post.slug %}">Editer</a>
                    <a href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
                </div>
                {% endif %}
            </div>
            <h5 class='post-author'>Publie par <i>{{post.author_or_unnone}}</i> le {{post.created_on|date:'j F Y'}}</h5>
            <p class = 'post-excerpt'>{{post.content|safe|truncatewords:50}}</p>

            <form action="{% url 'posts:detail' slug=post.slug %}">
                <button class = "btn btn-submit"> Lire l'article</button>
            </form>
        </article>S
    {% endfor %}
{% endblock %}

TheBlog/posts/templates/posts/blogpost_update.html
{% extends 'base.html' %}

{% block title%}Editer un article{% endblock %}


{% block content%}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value = 'Editer'  class='btn btn-submit'>
</form>
{% endblock %}

TheBlog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} {% endblock %}</title>
    
</head>
<body>
    <nav>
        <a href="{% url 'posts:home' %}">Accueil</a>

        {% if request.user.is_authenticated %}
        <a href="{% url 'posts:create' %}">Ajouter un article</a>
        {% endif %}
    </nav>
    <section id="blog">
        {% block content %}
        {% endblock %}
    </section>
</body>
</html>